//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAPS_LR6_Client.webservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webservice.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise", ReplyAction="http://tempuri.org/IService1/reiseResponse")]
        string[] reise(string m1, string m2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise", ReplyAction="http://tempuri.org/IService1/reiseResponse")]
        System.Threading.Tasks.Task<string[]> reiseAsync(string m1, string m2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise_otkuda", ReplyAction="http://tempuri.org/IService1/reise_otkudaResponse")]
        string[] reise_otkuda(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise_otkuda", ReplyAction="http://tempuri.org/IService1/reise_otkudaResponse")]
        System.Threading.Tasks.Task<string[]> reise_otkudaAsync(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise_kuda", ReplyAction="http://tempuri.org/IService1/reise_kudaResponse")]
        string[] reise_kuda(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/reise_kuda", ReplyAction="http://tempuri.org/IService1/reise_kudaResponse")]
        System.Threading.Tasks.Task<string[]> reise_kudaAsync(string m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bron", ReplyAction="http://tempuri.org/IService1/bronResponse")]
        string bron(int n, int k);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/bron", ReplyAction="http://tempuri.org/IService1/bronResponse")]
        System.Threading.Tasks.Task<string> bronAsync(int n, int k);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PAPS_LR6_Client.webservice.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PAPS_LR6_Client.webservice.IService1>, PAPS_LR6_Client.webservice.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] reise(string m1, string m2) {
            return base.Channel.reise(m1, m2);
        }
        
        public System.Threading.Tasks.Task<string[]> reiseAsync(string m1, string m2) {
            return base.Channel.reiseAsync(m1, m2);
        }
        
        public string[] reise_otkuda(string m) {
            return base.Channel.reise_otkuda(m);
        }
        
        public System.Threading.Tasks.Task<string[]> reise_otkudaAsync(string m) {
            return base.Channel.reise_otkudaAsync(m);
        }
        
        public string[] reise_kuda(string m) {
            return base.Channel.reise_kuda(m);
        }
        
        public System.Threading.Tasks.Task<string[]> reise_kudaAsync(string m) {
            return base.Channel.reise_kudaAsync(m);
        }
        
        public string bron(int n, int k) {
            return base.Channel.bron(n, k);
        }
        
        public System.Threading.Tasks.Task<string> bronAsync(int n, int k) {
            return base.Channel.bronAsync(n, k);
        }
    }
}
